name: Builds & pushes frontend to AWS

on:
  push:
    branches:
      - feature/pipeline
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Clone from prez-ui
        run: git clone https://github.com/RDFLib/prez-ui.git
      - name: Install and build
        run: |
          cd prez-ui
          npm ci
          CI=false npm run build
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          VITE_MAP_SEARCH_PROPS_FC_LABEL: https://schema.org/name
          VITE_MAP_SEARCH_PROPS_DS_LABEL: https://schema.org/name
          VITE_MAP_SETTINGS_API_KEY: ${{ secrets.VITE_MAP_SETTINGS_API_KEY }}
      - name: Copy theme files
        run: |
          cd prez-ui
          cp -R dist ../
          cd ..
          cp -R theme dist/
          rm -rf prez-ui/
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: Clear S3 bucket
        run: aws s3 rm s3://${{ secrets.S3_BUCKET_NAME }} --recursive
      - name: Upload to S3
        run: aws s3 cp dist/ s3://${{ secrets.S3_BUCKET_NAME }} --recursive
